-- Screener.in fundamentals cached on the personal stock registry.

alter table public.registry_stocks
  add column if not exists book_value double precision,
  add column if not exists dividend_yield double precision,
  add column if not exists roce double precision,
  add column if not exists roe double precision,
  add column if not exists face_value double precision,
  add column if not exists high_low text,
  add column if not exists sales_growth_3y double precision,
  add column if not exists sales_growth_5y double precision,
  add column if not exists sales_growth_10y double precision,
  add column if not exists sales_growth_ttm double precision,
  add column if not exists profit_growth_3y double precision,
  add column if not exists profit_growth_5y double precision,
  add column if not exists profit_growth_10y double precision,
  add column if not exists profit_growth_ttm double precision,
  add column if not exists stock_cagr_1y double precision,
  add column if not exists stock_cagr_3y double precision,
  add column if not exists stock_cagr_5y double precision,
  add column if not exists stock_cagr_10y double precision,
  add column if not exists promoter_holding double precision,
  add column if not exists fii_holding double precision,
  add column if not exists dii_holding double precision,
  add column if not exists public_holding double precision,
  add column if not exists government_holding double precision,
  add column if not exists other_holding double precision,
  add column if not exists quarterly_results jsonb default '{}'::jsonb,
  add column if not exists profit_loss jsonb default '{}'::jsonb,
  add column if not exists shareholding jsonb default '{}'::jsonb,
  add column if not exists screener_url text,
  add column if not exists screener_fetched_at bigint;
